// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3nHNpHmQdM50vmAqEyFW80vbEon4BZ7o',
    appId: '1:30564052181:web:a03d9099d8705ee02fc65c',
    messagingSenderId: '30564052181',
    projectId: 'project-11ba2',
    authDomain: 'project-11ba2.firebaseapp.com',
    storageBucket: 'project-11ba2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2XIBcI4_484lzf_joSo1BLetAFXjiKE',
    appId: '1:30564052181:android:62197ad3160e1d422fc65c',
    messagingSenderId: '30564052181',
    projectId: 'project-11ba2',
    storageBucket: 'project-11ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdda4Xp9Bi9HY4X8a3rs0XOJyXYjpr-Zk',
    appId: '1:30564052181:ios:ffdad115cecb11952fc65c',
    messagingSenderId: '30564052181',
    projectId: 'project-11ba2',
    storageBucket: 'project-11ba2.firebasestorage.app',
    iosBundleId: 'com.example.projectManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdda4Xp9Bi9HY4X8a3rs0XOJyXYjpr-Zk',
    appId: '1:30564052181:ios:ffdad115cecb11952fc65c',
    messagingSenderId: '30564052181',
    projectId: 'project-11ba2',
    storageBucket: 'project-11ba2.firebasestorage.app',
    iosBundleId: 'com.example.projectManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3nHNpHmQdM50vmAqEyFW80vbEon4BZ7o',
    appId: '1:30564052181:web:e31d006f16ef62492fc65c',
    messagingSenderId: '30564052181',
    projectId: 'project-11ba2',
    authDomain: 'project-11ba2.firebaseapp.com',
    storageBucket: 'project-11ba2.firebasestorage.app',
  );
}
